language: cpp

sudo: false

cache:
  directories:
    - lib/curl
    - lib/boost_1_63_0

git:
  depth: 1

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
          env: COMPILER_CXX='g++-7' COMPILER_CC='gcc-7'

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-5.0', 'ubuntu-toolchain-r-test']
          packages: ['clang-5.0']
          env: COMPILER_CXX='clang++-5.0' COMPILER_CC='clang-5.0'

before_install:
  - cd pol-core/bin-build

before_script:
  - echo 'Configure...' && echo -en 'travis_fold:start:script.configure\\r'
  - export TRAVIS_CI=1
  - export CXX=${COMPILER_CXX}
  - export CC=${COMPILER_CC}
  - cmake ../..
  - echo -en 'travis_fold:end:script.configure\\r'

script:
  - echo 'Build...' && echo -en 'travis_fold:start:script.build\\r'
  - make -j 2
  - echo -en 'travis_fold:end:script.build\\r'

  - echo 'Tests...' && echo -en 'travis_fold:start:script.tests\\r'
  - cd ../../testsuite/escript
  - ./performtests.py ../../pol-core/bin/ecompile ../../pol-core/bin/runecl -n 5;
  - echo -en 'travis_fold:end:script.tests\\r'

notifications:
  email:
    - polteam@polserver.com
